### ISSUE TITLE
automatic ui error

### ISSUE THREAD

**Issue by jekanev** [AbdBarho/stable-diffusion-webui-docker#123]
error when start automatic ui

```
webui-docker-auto-1  | + python3 -u ../../webui.py --listen --port 7860 --hide-ui-dir-config --ckpt-dir /stable-diffusion-webui/models/Stable-diffusion --allow-code --medvram
webui-docker-auto-1  | Warning: Taming Transformers not found at path /stable-diffusion-webui/repositories/taming-transformers/taming
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/../../webui.py", line 82, in <module>
webui-docker-auto-1  |     shared.sd_model = modules.sd_models.load_model()
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 171, in load_model
webui-docker-auto-1  |     sd_model = instantiate_from_config(sd_config.model)
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
webui-docker-auto-1  |     return get_obj_from_str(config["target"])(**config.get("params", dict()))
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/util.py", line 93, in get_obj_from_str
webui-docker-auto-1  |     return getattr(importlib.import_module(module, package=None), cls)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
webui-docker-auto-1  |     return _bootstrap._gcd_import(name[level:], package, level)
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
webui-docker-auto-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 24, in <module>
webui-docker-auto-1  |     from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/autoencoder.py", line 6, in <module>
webui-docker-auto-1  |     from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
webui-docker-auto-1  | ModuleNotFoundError: No module named 'taming'
webui-docker-auto-1 exited with code 1
```
first i run
docker compose --profile download up --build
then 
docker compose --profile auto up --build

i run bash inside
```
root@1fa9760f3875:/stable-diffusion-webui/repositories/stable-diffusion# ls ../
BLIP  CodeFormer  k-diffusion  latent-diffusion  stable-diffusion
```
seem i can fix it with git and all work well
`git clone https://github.com/CompVis/taming-transformers.git repositories/taming-transformers`
but not working with default setup.

**Comment by AbdBarho** [comment]
that is strange,
the repo is cloned explicitly in the dockerfile, https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/services/AUTOMATIC1111/Dockerfile#L15

do you have the most up-to-date state of this repo?

**Comment by jekanev** [comment]
> that is strange, the repo is cloned explicitly in the dockerfile, https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/master/services/AUTOMATIC1111/Dockerfile#L15
> 
> do you have the most up-to-date state of this repo?

yes i `git pull origin maser` right before run setup commands.

**Comment by AbdBarho** [comment]
@jekanev oh OH! thats a bug. would you like to contribute a fix? add the missing `cd ...` ?

**Comment by jekanev** [comment]
> @jekanev oh OH! thats a bug. would you like to contribute a fix? add the missing `cd ...` ?

i not testing it just suggested. i can try do this after test. if test pass should i do pull request? or just drop diff in comments? i kinda amateur in programming.

**Comment by AbdBarho** [comment]
Yes! that's it!

Would you create pull request?
