### ISSUE TITLE
AUTOMATIC's folk missing module 'taming' 

### ISSUE THREAD

**Issue by chenjunnn** [AbdBarho/stable-diffusion-webui-docker#133]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

```shell
➜  stable-diffusion-webui-docker git:(master) git reset --hard
HEAD is now at b60c787 Update bug.md
➜  stable-diffusion-webui-docker git:(master) git pull
Already up to date.
➜  stable-diffusion-webui-docker git:(master) docker compose --profile auto up --build
[+] Building 4.5s (27/27) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                         1.9s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ce  0.0s
 => [internal] load build definition from Dockerfile                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => [internal] load metadata for docker.io/alpine/git:2.36.2                                                       1.9s
 => [internal] load metadata for docker.io/library/python:3.10-slim                                                2.1s
 => [download 1/6] FROM docker.io/alpine/git:2.36.2@sha256:ec491c893597b68c92b88023827faa771772cfd5e106b76c713fa5  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 118B                                                                                  0.0s
 => [stage-1  1/11] FROM docker.io/library/python:3.10-slim@sha256:f2ee145f3bc4e061f8dfe7e6ebd427a410121495a0bd26  0.0s
 => CACHED [stage-1  2/11] RUN pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https:  0.0s
 => CACHED [stage-1  3/11] RUN apt-get update && apt install fonts-dejavu-core rsync git -y && apt-get clean       0.0s
 => CACHED [stage-1  4/11] RUN <<EOF (git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git...)    0.0s
 => CACHED [download 2/6] RUN git clone https://github.com/CompVis/stable-diffusion.git repositories/stable-diffu  0.0s
 => CACHED [download 3/6] RUN git clone https://github.com/sczhou/CodeFormer.git repositories/CodeFormer && cd re  0.0s
 => CACHED [download 4/6] RUN git clone https://github.com/salesforce/BLIP.git repositories/BLIP && cd repositori  0.0s
 => CACHED [download 5/6] RUN <<EOF (# because taming-transformers is huge...)                                     0.0s
 => CACHED [download 6/6] RUN git clone https://github.com/crowsonkb/k-diffusion.git repositories/k-diffusion &&   0.0s
 => CACHED [stage-1  5/11] COPY --from=download /git/ /stable-diffusion-webui                                      0.0s
 => CACHED [stage-1  6/11] RUN pip install --prefer-binary --no-cache-dir -r /stable-diffusion-webui/repositories  0.0s
 => CACHED [stage-1  7/11] RUN <<EOF (cd stable-diffusion-webui...)                                                0.0s
 => CACHED [stage-1  8/11] RUN pip install --prefer-binary --no-cache-dir opencv-python-headless   git+https://gi  0.0s
 => CACHED [stage-1  9/11] COPY . /docker                                                                          0.0s
 => CACHED [stage-1 10/11] RUN <<EOF (chmod +x /docker/mount.sh && python3 /docker/info.py /stable-diffusion-webu  0.0s
 => CACHED [stage-1 11/11] WORKDIR /stable-diffusion-webui/repositories/stable-diffusion                           0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:31345fa7a4ca2715fbb125a562ef9e90ddcc99c4ce8d7fdaaa931da8dad89924                       0.0s
 => => naming to docker.io/library/webui-docker-auto                                                               0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 1/0
 ⠿ Container webui-docker-auto-1  Created                                                                          0.0s
Attaching to webui-docker-auto-1
webui-docker-auto-1  | + /docker/mount.sh
webui-docker-auto-1  | Mounted .cache
webui-docker-auto-1  | Mounted LDSR
webui-docker-auto-1  | Mounted Hypernetworks
webui-docker-auto-1  | Mounted GFPGAN
webui-docker-auto-1  | Mounted RealESRGAN
webui-docker-auto-1  | Mounted ScuNET
webui-docker-auto-1  | Mounted .cache
webui-docker-auto-1  | Mounted StableDiffusion
webui-docker-auto-1  | Mounted embeddings
webui-docker-auto-1  | Mounted ESRGAN
webui-docker-auto-1  | Mounted SwinIR
webui-docker-auto-1  | Mounted BSRGAN
webui-docker-auto-1  | Mounted Codeformer
webui-docker-auto-1  | + python3 -u ../../webui.py --listen --port 7860 --hide-ui-dir-config --ckpt-dir /stable-diffusion-webui/models/Stable-diffusion --allow-code --medvram
webui-docker-auto-1  | Warning: Taming Transformers not found at path /stable-diffusion-webui/repositories/taming-transformers/taming
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/../../webui.py", line 83, in <module>
webui-docker-auto-1  |     shared.sd_model = modules.sd_models.load_model()
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 181, in load_model
webui-docker-auto-1  |     sd_model = instantiate_from_config(sd_config.model)
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
webui-docker-auto-1  |     return get_obj_from_str(config["target"])(**config.get("params", dict()))
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/util.py", line 93, in get_obj_from_str
webui-docker-auto-1  |     return getattr(importlib.import_module(module, package=None), cls)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
webui-docker-auto-1  |     return _bootstrap._gcd_import(name[level:], package, level)
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
webui-docker-auto-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
webui-docker-auto-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 24, in <module>
webui-docker-auto-1  |     from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
webui-docker-auto-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/autoencoder.py", line 6, in <module>
webui-docker-auto-1  |     from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer
webui-docker-auto-1  | ModuleNotFoundError: No module named 'taming'
webui-docker-auto-1 exited with code 1
```

**Which UI**

auto

**Hardware / Software**
 - OS: [Windows 11 WSL2]

**Additional context**
It seems like the problem hasn't been fixed https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/123

**Comment by AbdBarho** [comment]
@chenjunnn it seems that the clone of the repo fails, without the build failing, I created a new branch that will show the error (in case there is any), can you check it out and tell me if it works? #134

**Comment by AbdBarho** [comment]
just for info:

the taming transformers repo is HUGE ~100MB for zip, more if you git clone, to the degree that the download might fail if your internet connection has a small hiccup.

**Comment by chenjunnn** [comment]
I wonder why the building process didn't cancel if the download failed.

**Comment by AbdBarho** [comment]
long story short, bash/sh only fail if the last command fails.
with the new flags it should fail if any command fails

**Comment by chenjunnn** [comment]
Thanks for answering!
