### ISSUE TITLE
Error when trying to create embedding (Expected all tensors to be on the same device)

### ISSUE THREAD

**Issue by xNissX233** [AbdBarho/stable-diffusion-webui-docker#143]
**Has this issue been opened before?**
No

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I tried to create an embedding in Textual inversion menu, but after clicking on "create" it says "Error" in red, and I get an error that says "Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! "

**Which UI**

auto

**Hardware / Software**
 - OS: Manjaro Linux
 - OS version: Latest
 - Docker Version: 1:20.10.18-1
 - Docker compose version: 2.11.2-1
 - Repo version: Latest release
 - RAM: 16Gb
 - GPU/VRAM: Nvidia Geforce GTX 1060/6Gb

**Steps to Reproduce**
1. sudo docker compose --profile auto up --build
2. Go to web interface and go to Textual inversion tab
3. Write a name for an embedding 
4. Click create
5. See error

**Additional context**

All the other features work fine afaik, and the GPU is working fine and fast.

Log: 

```
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 273, in run_predict
webui-docker-auto-1  |     output = await app.blocks.process_api(
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 742, in process_api
webui-docker-auto-1  |     result = await self.call_function(fn_index, inputs, iterator)
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 653, in call_function
webui-docker-auto-1  |     prediction = await anyio.to_thread.run_sync(
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
webui-docker-auto-1  |     return await get_asynclib().run_sync_in_worker_thread(
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
webui-docker-auto-1  |     return await future
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
webui-docker-auto-1  |     result = context.run(func, *args)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/textual_inversion/ui.py", line 11, in create_embedding
webui-docker-auto-1  |     filename = modules.textual_inversion.textual_inversion.create_embedding(name, nvpt, init_text=initialization_text)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 143, in create_embedding
webui-docker-auto-1  |     embedded = embedding_layer.token_embedding.wrapped(ids.to(devices.device)).squeeze(0)
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
webui-docker-auto-1  |     return forward_call(*input, **kwargs)
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
webui-docker-auto-1  |     return F.embedding(
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2183, in embedding
webui-docker-auto-1  |     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
webui-docker-auto-1  | RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
webui-docker-auto-1  | Loading weights [e1de58a9] from /stable-diffusion-webui/models/Stable-diffusion/wd-v1-3-full.ckpt
webui-docker-auto-1  | Global Step: 683410
webui-docker-auto-1  | Weights loaded.
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 273, in run_predict
webui-docker-auto-1  |     output = await app.blocks.process_api(
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 742, in process_api
webui-docker-auto-1  |     result = await self.call_function(fn_index, inputs, iterator)
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 653, in call_function
webui-docker-auto-1  |     prediction = await anyio.to_thread.run_sync(
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
webui-docker-auto-1  |     return await get_asynclib().run_sync_in_worker_thread(
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
webui-docker-auto-1  |     return await future
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
webui-docker-auto-1  |     result = context.run(func, *args)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/textual_inversion/ui.py", line 11, in create_embedding
webui-docker-auto-1  |     filename = modules.textual_inversion.textual_inversion.create_embedding(name, nvpt, init_text=initialization_text)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 143, in create_embedding
webui-docker-auto-1  |     embedded = embedding_layer.token_embedding.wrapped(ids.to(devices.device)).squeeze(0)
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
webui-docker-auto-1  |     return forward_call(*input, **kwargs)
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
webui-docker-auto-1  |     return F.embedding(
webui-docker-auto-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2183, in embedding
webui-docker-auto-1  |     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
webui-docker-auto-1  | RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

**Comment by AbdBarho** [comment]
@RBNXI You  are using an old version, the WebUI does not use neither python3.8 nor conda.

**Comment by AbdBarho** [comment]
did you use git? switch to latest master

**Comment by AbdBarho** [comment]
a lot has changed in the last 8 days.

Do you use git? it would be a lot easier for you if you just `git clone` the project.

**Comment by AbdBarho** [comment]
@RBNXI after a while of debugging, turned out that you cannot train anything if you have the `--medvram` flag, which is set per default in the `docker-compose.yml` file, you can remove it and try again. It did not work on my machine (also 1060/6GB) because out of memory.

**Comment by AbdBarho** [comment]
> Could you please add this information to the readme?, I think it could be very useful for everyone, and since you made the effort of getting that information, it would be a shame to not use it.

In that case, I would basically have to always copy/paste the entire documentation of every UI.  I think  its best if users look it up themselves. https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Textual-Inversion

> Oh and do you have any hint on why the history doesn't work neither?

Bug! #138, I have an MR that should close it #146 

> And also, one question totally unrelated: what's the directory referred in "Batch img2img" tab? is it in the data folder or somehow inaccessible in the docker folder?.

It was hidden because of the flag `--hide-ui-dir-config`, which I have also removed in #146.


Just for info, the `data` and `output` folder are mounted into the container as `/data` and `/output`, so if you want to input/output data to the container, use these paths.

**Comment by AbdBarho** [comment]
@RBNXI you can now try the stuff from master,  open the terminal and:
```
git pull origin master
docker compose --profile auto up --build
```
