### ISSUE TITLE
Auto: "Interrogate CLIP" not working

### ISSUE THREAD

**Issue by ProducerMatt** [AbdBarho/stable-diffusion-webui-docker#191]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Clicking "Interrogate CLIP" in AUTO gives the following error:
```
Error interrogating
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/interrogate.py", line 141, in interrogate
    self.load()
  File "/stable-diffusion-webui/modules/interrogate.py", line 70, in load
    self.blip_model = self.load_blip_model()
  File "/stable-diffusion-webui/modules/interrogate.py", line 48, in load_blip_model
    import models.blip
ModuleNotFoundError: No module named 'models.blip'
```

Googling suggests that this issue happens when you don't have `repositories/BLIP`. But I definitely do, it's part of the Dockerfile.

**Which UI**

Auto.

**Hardware / Software**
 - OS: Linux
 - OS version: NixOS
 - Docker Version: 20.10.21
 - Docker compose version: 2.12.2
 - Repo version: 9092aa233b91af2bb83a11f20b955ad78fe386af but with changes specified in the "deforum" how-to post
 - RAM: 16 gigs
 - GPU/VRAM: 1070 + 6g of VRAM IIRC

**Steps to Reproduce**
Go to img2img, click on "interrogate CLIP"

**Additional context**
When enabling deepdanbooru with the CLI flag and cloning the repo to the correct spot, it gives a similar "No module named deepdanbooru" error. Is Python supposed to have an extra include path for `./repositories/`?

**Comment by AbdBarho** [comment]
@ProducerMatt can you try to disable the deforum extensions and see  if that works?

just comment out the line:
```sh
export PYTHONPATH="$PY3D_PATH:$ADA_PATH:$MIDAS_PATH"
```
in `data/config/auto/startup.sh` and see if it works.

**Comment by ProducerMatt** [comment]
Good catch! commenting it out lets BLIP work again. 👍 

I wondered if it was overwriting a previous `$PYTHONPATH`, so I tried changing the line so it was prepending, like `export PYTHONPATH="$MIDAS_PATH:$PY3D_PATH:$FOOBAR_PATH:$PYTHONPATH`, but I got an error that $PYTHONPATH wasn't defined yet. So maybe it's preventing a new $PYTHONPATH from being set?

Side note, when BLIP is working, I get this error.
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 331, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/site-packages/gradio/templates/frontend/assets/index.e0c646e0.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/responses.py", line 334, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path /usr/local/lib/python3.10/site-packages/gradio/templates/frontend/assets/index.e0c646e0.js does not exist.
load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth
```

**Comment by DevilaN** [comment]
@AbdBarho:
Couple of things to think of:
1. We need some easy method to run service with clean container without any additional bloatware extensions with user inputted scripts, so it will be easy test to check whether bug shows up with "clean state of app" or not. Probably there shoud be default config jsons as well. We could think of some environment variable and modification of MOUNTS array in entrypoint script. Or something else.
2. A1111 allows installing extensions from webui. Sooner of later we will deal with it. Maybe @ProducerMatt could check whether there are issues or not with this new method of installing and those extensions mentioned in this issue?

**Comment by AbdBarho** [comment]
@DevilaN 
1. agree, in our case, this reduces to not running `startup.sh` on startup (if I am not missing anything)
2. I am assuming the installation would be: _download the extension to the `extensions` folder_. the only question would be how to manage the additional dependencies for the extension, I know that the UI runs `install.py` of an extension if it finds it
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/30b1bcc64e67ad50c5d3af3a6fe1bd1e9553f34e/launch.py#L108
I am not sure how it would be mirrored in this repo. I already have something similar described in the [wiki](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Usage#extensions), we will see.

**Comment by AbdBarho** [comment]
upstream https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4380

**Comment by AlexNolasco** [comment]
Problem still persists, 

 load checkpoint from /stable-diffusion-webui/models/BLIP/model_base_caption_capfilt_large.pth
 Error interrogating
 Traceback (most recent call last):
   File "/stable-diffusion-webui/modules/interrogate.py", line 148, in interrogate
     caption = self.generate_caption(pil_image)
   File "/stable-diffusion-webui/modules/interrogate.py", line 133, in generate_caption
     caption = self.blip_model.generate(gpu_image, sample=False, num_beams=shared.opts.interrogate_clip_num_beams, min_length=shared.opts.interrogate_clip_min_length, max_length=shared.opts.interrogate_clip_max_length)
   File "/stable-diffusion-webui/repositories/BLIP/models/blip.py", line 156, in generate
     outputs = self.text_decoder.generate(input_ids=input_ids,
   File "/usr/local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/transformers/generation_utils.py", line 1268, in generate
     self._validate_model_kwargs(model_kwargs.copy())
   File "/usr/local/lib/python3.10/site-packages/transformers/generation_utils.py", line 964, in _validate_model_kwargs
     raise ValueError(
 ValueError: The following `model_kwargs` are not used by the model: ['encoder_hidden_states', 'encoder_attention_mask'] (note: typos in the generate arguments will also show up in this list)
 
 Traceback (most recent call last):
   File "/stable-diffusion-webui/modules/interrogate.py", line 148, in interrogate
     caption = self.generate_caption(pil_image)
   File "/stable-diffusion-webui/modules/interrogate.py", line 133, in generate_caption
     caption = self.blip_model.generate(gpu_image, sample=False, num_beams=shared.opts.interrogate_clip_num_beams, min_length=shared.opts.interrogate_clip_min_length, max_length=shared.opts.interrogate_clip_max_length)
   File "/stable-diffusion-webui/repositories/BLIP/models/blip.py", line 156, in generate
     outputs = self.text_decoder.generate(input_ids=input_ids,
   File "/usr/local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/transformers/generation_utils.py", line 1268, in generate
     self._validate_model_kwargs(model_kwargs.copy())
   File "/usr/local/lib/python3.10/site-packages/transformers/generation_utils.py", line 964, in _validate_model_kwargs
     raise ValueError(
 ValueError: The following `model_kwargs` are not used by the model: ['encoder_hidden_states', 'encoder_attention_mask'] (note: typos in the generate arguments will also show up in this list)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 284, in run_predict
     output = await app.blocks.process_api(
   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 982, in process_api
     result = await self.call_function(fn_index, inputs, iterator)
   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 824, in call_function
     prediction = await anyio.to_thread.run_sync(
   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
     return await get_asynclib().run_sync_in_worker_thread(
   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
     return await future
   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
     result = context.run(func, *args)
   File "/stable-diffusion-webui/modules/ui.py", line 269, in interrogate
     prompt = shared.interrogator.interrogate(image)
   File "/stable-diffusion-webui/modules/interrogate.py", line 177, in interrogate
     res += "<error>"
 TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

**Comment by AbdBarho** [comment]
@AlexNolasco there hasn't been much activity when it comes to the development of `auto`, I guess this problem will stay open for a while...

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4380
