### ISSUE TITLE
Failed to build pycocotools; A new release of pip available: 22.2.2 -> 22.3.1; No module named 'accelerate'

### ISSUE THREAD

**Issue by Corshi** [AbdBarho/stable-diffusion-webui-docker#223]
```
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (pyproject.toml): started
  Building wheel for pycocotools (pyproject.toml): finished with status 'error'
Failed to build pycocotools

stderr:   error: subprocess-exited-with-error
  
  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/pycocotools
      copying pycocotools/mask.py -> build/lib.linux-x86_64-cpython-310/pycocotools
      copying pycocotools/coco.py -> build/lib.linux-x86_64-cpython-310/pycocotools
      copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-cpython-310/pycocotools
      copying pycocotools/__init__.py -> build/lib.linux-x86_64-cpython-310/pycocotools
      running build_ext
      cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
      /tmp/pip-build-env-2r15dc51/overlay/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-zr0mf5ev/pycocotools_cf1aaa4bb2ed4acdb2b9a6a2c7151dda/pycocotools/_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      building 'pycocotools._mask' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/common
      creating build/temp.linux-x86_64-cpython-310/pycocotools
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-2r15dc51/overlay/lib/python3.10/site-packages/numpy/core/include -I./common -I/usr/local/include/python3.10 -c ./common/maskApi.c -o build/temp.linux-x86_64-cpython-310/./common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip



Error loading script: main.py
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 27, in <module>
    from dreambooth.dreambooth import get_db_models
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'
```

Webui works fine really. I just see those errors every time I run it, and it bothers me. It happens for some days now.

_WEBUI AUTOMATIC1111 (auto)
Hardware / Software:_

    OS: Windows 11
    OS version: 2aH2 22000.652
    Docker&compose version: Latest
    RAM: 32GB
    GPU/VRAM: 8GB

**Comment by AbdBarho** [comment]
@Corshi this is probably related to the dreambooth extension, or maybe some 
 other extension, can you remove theem and see if the error remains?

**Comment by Corshi** [comment]
Oh sorry then. I did moved all the extensions out of the folder and errors are gone.
I did tried with only sd_dreambooth_extension at first, but it was not it - at least not only.

I will keep more attention to what extensions do that next time.

Thanks for the answer.
