### ISSUE TITLE
Can't generate images

### ISSUE THREAD

**Issue by a9a9a9a9a9a9a9a9** [AbdBarho/stable-diffusion-webui-docker#262]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I've generated images previously, but one of the more recent updates (last few weeks) has broken generation for me. It downloads, builds, and the browser tab interface opens just fine, but when I attempt to generate an image (whether it's img2img or txt2img) I get the following:
```
webui-docker-auto-cpu-1  | Error completing request
webui-docker-auto-cpu-1  | Arguments: ('a cat', '', 'None', 'None', 4, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 0, False, False, False, False, '', 1, '', 0, '', True, False, False) {}
webui-docker-auto-cpu-1  | Traceback (most recent call last):
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/modules/call_queue.py", line 45, in f
webui-docker-auto-cpu-1  |     res = list(func(*args, **kwargs))
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/modules/call_queue.py", line 28, in f
webui-docker-auto-cpu-1  |     res = func(*args, **kwargs)
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/modules/txt2img.py", line 49, in txt2img
webui-docker-auto-cpu-1  |     processed = process_images(p)
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/modules/processing.py", line 464, in process_images
webui-docker-auto-cpu-1  |     res = process_images_inner(p)
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/modules/processing.py", line 567, in process_images_inner
webui-docker-auto-cpu-1  |     samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/modules/processing.py", line 699, in sample
webui-docker-auto-cpu-1  |     samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/modules/processing.py", line 150, in txt2img_image_conditioning
webui-docker-auto-cpu-1  |     image_conditioning = self.sd_model.get_first_stage_encoding(self.sd_model.encode_first_stage(image_conditioning))
webui-docker-auto-cpu-1  |   File "/usr/local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
webui-docker-auto-cpu-1  |     return func(*args, **kwargs)
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 830, in encode_first_stage
webui-docker-auto-cpu-1  |     return self.first_stage_model.encode(x)
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/autoencoder.py", line 83, in encode
webui-docker-auto-cpu-1  |     h = self.encoder(x)
webui-docker-auto-cpu-1  |   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
webui-docker-auto-cpu-1  |     return forward_call(*input, **kwargs)
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/model.py", line 536, in forward
webui-docker-auto-cpu-1  |     h = self.mid.attn_1(h)
webui-docker-auto-cpu-1  |   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
webui-docker-auto-cpu-1  |     return forward_call(*input, **kwargs)
webui-docker-auto-cpu-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/model.py", line 258, in forward
webui-docker-auto-cpu-1  |     out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)
webui-docker-auto-cpu-1  |   File "/usr/local/lib/python3.10/site-packages/xformers/ops/memory_efficient_attention.py", line 963, in memory_efficient_attention
webui-docker-auto-cpu-1  |     ).op
webui-docker-auto-cpu-1  |   File "/usr/local/lib/python3.10/site-packages/xformers/ops/memory_efficient_attention.py", line 821, in op
webui-docker-auto-cpu-1  |     raise NotImplementedError(f"No operator found for this attention: {self}")
webui-docker-auto-cpu-1  | NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cpu'), k=512, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=4096, q_len=4096, kv=512, batch_size=1, num_heads=1, has_custom_scale=False, requires_grad=False)
webui-docker-auto-cpu-1  |
```

**Which UI**

auto-cpu

**Hardware / Software**

- OS: Windows 11
- OS version: 22H2
- WSL version (if applicable): 2
- Docker Version: 20.10.17
- Docker compose version: 2.10.2
- Repo version: I can't figure out how to do this but I'm fully up to date as of posting this.
- RAM: 32 GB
- GPU/VRAM:

**Steps to Reproduce**

1. Build
2. attempt to generate an image using txt2img, nothing happens in the interface
3. Errors in command prompt

**Comment by AbdBarho** [comment]
@a9a9a9a9a9a9a9a9 Use sd v1.4 or v1.5 models, newer models v2.0 and 2.1 are hardcoded to work with `xformers` which is GPU only.

**Comment by a9a9a9a9a9a9a9a9** [comment]
Ok, so I started it up again, and the model selection dropdown was blank, so I picked 1.5 pruned ema only and tried generating. Same result, doesn't generate and returns the same stuff. Tried 1.5 inpainting just to be sure. Also deleted it and downloaded it again to make sure I hadn't put any 2.0 models in there, because I had tried that. Still does the same thing.

**Comment by AbdBarho** [comment]
are you using any extensions? what are your cli flags?

**Comment by AbdBarho** [comment]
probably related https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/5794
