### ISSUE TITLE
Getting an error due to missing checkpoint file

### ISSUE THREAD

**Issue by sausax** [AbdBarho/stable-diffusion-webui-docker#3]
Getting following error after running `docker-compose up --build`

```
model_1  | Loading model from /models/model.ckpt
model_1  | Traceback (most recent call last):
model_1  |   File "scripts/webui.py", line 308, in <module>
model_1  |     sd = load_sd_from_config(opt.ckpt)
model_1  |   File "scripts/webui.py", line 140, in load_sd_from_config
model_1  |     pl_sd = torch.load(ckpt, map_location="cpu")
model_1  |   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
model_1  |     with _open_file_like(f, 'rb') as opened_file:
model_1  |   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
model_1  |     return _open_file(name_or_buffer, mode)
model_1  |   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
model_1  |     super(_open_file, self).__init__(open(name, mode))
model_1  | FileNotFoundError: [Errno 2] No such file or directory: '/models/model.ckpt'
```

**Comment by sausax** [comment]
missed the point in readme

**Comment by AbdBarho** [comment]
Hi @sausax, glad your problem got fixed. However, this could be an indicator that the README or documentation in general is not clear or user-friendly enough, and some stuff might get lost under the rug.

If you feel that that is the case, I am very open to suggestions on how to improve the documentation. If not, please close this issue (again).

**Comment by sausax** [comment]
No....docs are clear. I was just to0 impatient.
