### ISSUE TITLE
 RuntimeError: Cannot add middleware after an application has started

### ISSUE THREAD

**Issue by God-of-meep** [AbdBarho/stable-diffusion-webui-docker#334]
**Has this issue been opened before?**

- [X] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

When i Ran the following code 

docker compose --profile auto up --build

It started doing its thing and at the end i receive this error  (Posting full output)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
webui-docker-auto-1  | Mounted extensions
webui-docker-auto-1  | + python3 -u webui.py --listen --port 7860 --allow-code --medvram --xformers --enable-insecure-extension-access --api
webui-docker-auto-1  | Removing empty folder: /stable-diffusion-webui/models/BSRGAN
webui-docker-auto-1  | LatentInpaintDiffusion: Running in eps-prediction mode
webui-docker-auto-1  | DiffusionWrapper has 859.54 M params.
webui-docker-auto-1  | Loading weights [3e16efc8] from /stable-diffusion-webui/models/Stable-diffusion/sd-v1-5-inpainting.ckpt
webui-docker-auto-1  | Applying xformers cross attention optimization.
webui-docker-auto-1  | Textual inversion embeddings loaded(0):
webui-docker-auto-1  | Model loaded in 16.6s (0.7s create model, 15.6s load weights).
webui-docker-auto-1  | Running on local URL:  http://0.0.0.0:7860
webui-docker-auto-1  |
webui-docker-auto-1  | To create a public link, set `share=True` in `launch()`.
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/webui.py", line 213, in <module>
webui-docker-auto-1  |     webui()
webui-docker-auto-1  |   File "/stable-diffusion-webui/webui.py", line 180, in webui
webui-docker-auto-1  |     app.add_middleware(GZipMiddleware, minimum_size=1000)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 135, in add_middleware
webui-docker-auto-1  |     raise RuntimeError("Cannot add middleware after an application has started")
webui-docker-auto-1  | RuntimeError: Cannot add middleware after an application has started
webui-docker-auto-1 exited with code 1


**Which UI**

**auto** 

**Hardware / Software**

- OS: Windows home 
- OS version: 22H2
- WSL version (if applicable): WSL version: 1.0.3.0

- Docker Version: Server: Docker Desktop 4.16.3 (96739)
                              Engine:
                                  Version:          20.10.22

- Docker compose version: v2.15.1
- Repo version: 5.0.0 <!-- tag, commit sha, or "from master" -->
- RAM: 16Gb
- GPU/VRAM: NVDIA Geforce RTX 2080 , VRam: 8192MB

**Steps to Reproduce**

I Just Ran the docker compose --profile auto up --build, and it Happens 

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

i very much could just be stupid but its best to ask for a pros help, and i hope to be of help as well 

thx

**Comment by AbdBarho** [comment]
can you update to the latest commit from master? this problem should be fixed.

**Comment by God-of-meep** [comment]
Will Try that now and Reply back with how i go
