### ISSUE TITLE
A dependency is broken, meaning this won't build

### ISSUE THREAD

**Issue by StoneCypher** [AbdBarho/stable-diffusion-webui-docker#339]
Hello.  One of the dependencies in the toolchain, `FastAPI`, released a `0.91` which causes a fault in the startup process.

```
webui-docker-auto-1  | Loading weights [cc6cb27103] from /stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
webui-docker-auto-1  | Creating model from config: /stable-diffusion-webui/configs/v1-inference.yaml
webui-docker-auto-1  | LatentDiffusion: Running in eps-prediction mode
webui-docker-auto-1  | DiffusionWrapper has 859.52 M params.
webui-docker-auto-1  | Applying xformers cross attention optimization.
webui-docker-auto-1  | Textual inversion embeddings loaded(0):
webui-docker-auto-1  | Model loaded in 4.0s (load weights from disk: 2.0s, create model: 0.5s, apply weights to model: 0.3s, apply half(): 0.2s, load VAE: 1.0s).
webui-docker-auto-1  | Running on local URL:  http://0.0.0.0:7860
webui-docker-auto-1  |
webui-docker-auto-1  | To create a public link, set `share=True` in `launch()`.
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/webui.py", line 278, in <module>
webui-docker-auto-1  |     webui()
webui-docker-auto-1  |   File "/stable-diffusion-webui/webui.py", line 232, in webui
webui-docker-auto-1  |     app.add_middleware(GZipMiddleware, minimum_size=1000)
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 135, in add_middleware
webui-docker-auto-1  |     raise RuntimeError("Cannot add middleware after an application has started")
webui-docker-auto-1  | RuntimeError: Cannot add middleware after an application has started
webui-docker-auto-1 exited with code 1
```

The A1111 community solves it by manually pinning the dependency in question to 0.90.1 and rebuilding, but it's not clear how to do that from within this docker image.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/7749

**Comment by AbdBarho** [comment]
@StoneCypher you are not running from latest master, this problem should be fixed.
