### ISSUE TITLE
WebUI does not load

### ISSUE THREAD

**Issue by Pyroglyph** [AbdBarho/stable-diffusion-webui-docker#359]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

The WebUI never loads. The container appears to launch normally (the latest log line is `To create a public link, set 'share=True' in 'launch()'.`) but when attempting to load the WebUI in a browser it just loads forever. A call to `curl http://localhost:7860/` also runs forever.
When the container is shut down, the error message in [this issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2287) occurs.
This did not happen with `sd-auto:41`, which is the previous version I had installed. Now even that doesn't work (it exhibits the same problem as this).

**Which UI**

auto

**Hardware / Software**

- OS: Windows 11
- OS version: 21H2 (build 22000.376)
- WSL version (if applicable): 2
- Docker Version: 20.10.23
- Docker compose version: 2.15.1
- Repo version: aa69f112302d29d667f20c9ccbe243c10834f6a2
- RAM: 16GB
- GPU/VRAM: RTX 3090 24GB

**Steps to Reproduce**

1. Build the `download` profile. Wait for it to finish successfully.
2. Build the `auto` profile. Wait for it to succeed and launch (i.e. wait until you see the "Running on local URL" log line)
4. Visit `http://localhost:7860/` as normal.
5. It never loads.

**Additional context**
 Upon re-running the container after the SIGINT occurs, I get this in the logs instead of it appearing normal.

```
2023-03-09 12:36:15 Mounted .cache
2023-03-09 12:36:15 Mounted LDSR
2023-03-09 12:36:15 Mounted BLIP
2023-03-09 12:36:15 Mounted Hypernetworks
2023-03-09 12:36:15 Mounted VAE
2023-03-09 12:36:15 Mounted GFPGAN
2023-03-09 12:36:15 Mounted RealESRGAN
2023-03-09 12:36:15 Mounted Deepdanbooru
2023-03-09 12:36:15 Mounted ScuNET
2023-03-09 12:36:15 Mounted .cache
2023-03-09 12:36:15 Mounted StableDiffusion
2023-03-09 12:36:15 Mounted embeddings
2023-03-09 12:36:15 Mounted ESRGAN
2023-03-09 12:36:15 Mounted config.json
2023-03-09 12:36:15 Mounted SwinIR
2023-03-09 12:36:16 Mounted Lora
2023-03-09 12:36:16 Mounted MiDaS
2023-03-09 12:36:16 Mounted ui-config.json
2023-03-09 12:36:16 Mounted BSRGAN
2023-03-09 12:36:16 Mounted Codeformer
2023-03-09 12:36:16 Mounted extensions
2023-03-09 12:36:16 + python -u webui.py --listen --port 7860 --allow-code --medvram --xformers --enable-insecure-extension-access --api
2023-03-09 12:36:26 Removing empty folder: /stable-diffusion-webui/models/BSRGAN
2023-03-09 12:36:28 Loading weights [3a17d0deff] from /stable-diffusion-webui/models/Stable-diffusion/realism/chilloutmix_NiCkpt.ckpt
2023-03-09 12:36:51 Creating model from config: /stable-diffusion-webui/configs/v1-inference.yaml
2023-03-09 12:36:51 LatentDiffusion: Running in eps-prediction mode
2023-03-09 12:36:51 DiffusionWrapper has 859.52 M params.
2023-03-09 12:37:21 Applying xformers cross attention optimization.
2023-03-09 12:37:21 Textual inversion embeddings loaded(0): 
2023-03-09 12:37:21 Model loaded in 53.7s (load weights from disk: 23.2s, create model: 0.8s, apply weights to model: 14.4s, apply half(): 5.6s, load VAE: 9.5s, load textual inversion embeddings: 0.2s).
2023-03-09 12:37:28 Traceback (most recent call last):
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
2023-03-09 12:37:28     six.raise_from(e, None)
2023-03-09 12:37:28   File "<string>", line 3, in raise_from
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
2023-03-09 12:37:28     httplib_response = conn.getresponse()
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
2023-03-09 12:37:28     response.begin()
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
2023-03-09 12:37:28     version, status, reason = self._read_status()
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
2023-03-09 12:37:28     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
2023-03-09 12:37:28     return self._sock.recv_into(b)
2023-03-09 12:37:28 TimeoutError: timed out
2023-03-09 12:37:28 
2023-03-09 12:37:28 During handling of the above exception, another exception occurred:
2023-03-09 12:37:28 
2023-03-09 12:37:28 Traceback (most recent call last):
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
2023-03-09 12:37:28     resp = conn.urlopen(
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
2023-03-09 12:37:28     retries = retries.increment(
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
2023-03-09 12:37:28     raise six.reraise(type(error), error, _stacktrace)
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
2023-03-09 12:37:28     raise value
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
2023-03-09 12:37:28     httplib_response = self._make_request(
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
2023-03-09 12:37:28     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
2023-03-09 12:37:28     raise ReadTimeoutError(
2023-03-09 12:37:28 urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=7860): Read timed out. (read timeout=3)
2023-03-09 12:37:28 
2023-03-09 12:37:28 During handling of the above exception, another exception occurred:
2023-03-09 12:37:28 
2023-03-09 12:37:28 Traceback (most recent call last):
2023-03-09 12:37:28   File "/stable-diffusion-webui/webui.py", line 286, in <module>
2023-03-09 12:37:28     webui()
2023-03-09 12:37:28   File "/stable-diffusion-webui/webui.py", line 218, in webui
2023-03-09 12:37:28     app, local_url, share_url = shared.demo.launch(
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1417, in launch
2023-03-09 12:37:28     if _frontend and (not networking.url_ok(self.local_url)) and (not self.share):
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/gradio/networking.py", line 179, in url_ok
2023-03-09 12:37:28     r = requests.head(url, timeout=3, verify=False)
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 104, in head
2023-03-09 12:37:28     return request('head', url, **kwargs)
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 61, in request
2023-03-09 12:37:28     return session.request(method=method, url=url, **kwargs)
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
2023-03-09 12:37:28     resp = self.send(prep, **send_kwargs)
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
2023-03-09 12:37:28     r = adapter.send(request, **kwargs)
2023-03-09 12:37:28   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 529, in send
2023-03-09 12:37:28     raise ReadTimeout(e, request=request)
2023-03-09 12:37:28 requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=7860): Read timed out. (read timeout=3)
```

I've also tried editing the config so it attempts to load a different safetensors model on startup. No dice.

It's suspicious to me that even the older image that I was running mere minutes before updating is now broken in the same way. It could be a clue as to what's going wrong?

**Comment by Pyroglyph** [comment]
Just found someone else who also seems to have [the same issue](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8418) over on A111's repo. Perhaps it's a problem there and not here?

**Comment by AbdBarho** [comment]
Yeah, that might be the case, it also seems like an internet problem.
