### ISSUE TITLE
RuntimeError: shape '[768, 3072]' is invalid for input of size 618407

### ISSUE THREAD

**Issue by fireqong** [AbdBarho/stable-diffusion-webui-docker#395]
os: windows10
python version: 3.10.10

(sd) D:\stable-diffusion-webui>webui-user.bat
venv "D:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
Launching Web UI with arguments: --skip-torch-cuda-test
No module 'xformers'. Proceeding without it.
Loading weights [15e24af181] from D:\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\webui.py", line 139, in initialize
    modules.sd_models.load_model()
  File "D:\stable-diffusion-webui\modules\sd_models.py", line 415, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "D:\stable-diffusion-webui\modules\sd_models.py", line 262, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "D:\stable-diffusion-webui\modules\sd_models.py", line 241, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 101, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: shape '[768, 3072]' is invalid for input of size 618407

**Comment by AbdBarho** [comment]
Wrong repo
https://github.com/AUTOMATIC1111/stable-diffusion-webui
