### ISSUE TITLE
Error reported during plugin installation

### ISSUE THREAD

**Issue by zhubao315** [AbdBarho/stable-diffusion-webui-docker#463]
The following error was reported when installing the plugin:

Error completing request
Arguments: ('https://github.com/Leodotpy/sd-pixel.git', ['ads', 'localization', 'installed'], 0, '') {}
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/stable-diffusion-webui/modules/ui_extensions.py", line 372, in install_extension_from_index
    ext_table, message = install_extension_from_url(None, url)
  File "/stable-diffusion-webui/modules/ui_extensions.py", line 320, in install_extension_from_url
    check_access()
  File "/stable-diffusion-webui/modules/ui_extensions.py", line 24, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
AssertionError: extension access disabled because of command line flags

How to add startup parameters?
./webui.sh --share --no-gradio-queue --enable-insecure-extension-access

**Comment by AbdBarho** [comment]
https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Usage
