### ISSUE TITLE
zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/libtorch_cuda.so'

### ISSUE THREAD

**Issue by Abdullah-AlAttar** [AbdBarho/stable-diffusion-webui-docker#508]
**Has this issue been opened before?**

- [ x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

tried to run auto UI after the recent update. I get the error
```
 > [auto stage-2  4/15] RUN --mount=type=cache,target=/cache --mount=type=cache,target=/root/.cache/pip   aria2c -x 5 --dir /cache --out torch-2.0.1-cp310-cp310-linux_x86_64.whl -c   https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-linux_x86_64.whl &&   pip install /cache/torch-2.0.1-cp310-cp310-linux_x86_64.whl torchvision --index-url https://download.pytorch.org/whl/cu118: 
#0 0.240                                                                                            
#0 0.240 06/13 21:21:33 [NOTICE] Downloading 1 item(s)
#0 0.641 
#0 0.641 06/13 21:21:33 [NOTICE] GID#ef0c27162cdf3db3 - Download has already completed: /cache/torch-2.0.1-cp310-cp310-linux_x86_64.whl
#0 0.641 
#0 0.641 06/13 21:21:33 [NOTICE] Download complete: /cache/torch-2.0.1-cp310-cp310-linux_x86_64.whl
#0 0.641 
#0 0.641 Download Results:
#0 0.641 gid   |stat|avg speed  |path/URI
#0 0.641 ======+====+===========+=======================================================
#0 0.641 ef0c27|OK  |       0B/s|/cache/torch-2.0.1-cp310-cp310-linux_x86_64.whl
#0 0.641 
#0 0.641 Status Legend:
#0 0.641 (OK):download completed.
#0 0.965 Looking in indexes: https://download.pytorch.org/whl/cu118
#0 0.972 Processing /cache/torch-2.0.1-cp310-cp310-linux_x86_64.whl
#0 6.879 Collecting torchvision
#0 6.951   Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.2%2Bcu118-cp310-cp310-linux_x86_64.whl (6.1 MB)
#0 7.751 Collecting filelock (from torch==2.0.1)
#0 7.767   Using cached https://download.pytorch.org/whl/filelock-3.9.0-py3-none-any.whl (9.7 kB)
#0 8.389 Collecting typing-extensions (from torch==2.0.1)
#0 8.407   Using cached https://download.pytorch.org/whl/typing_extensions-4.4.0-py3-none-any.whl (26 kB)
#0 8.827 Collecting sympy (from torch==2.0.1)
#0 8.933   Using cached https://download.pytorch.org/whl/sympy-1.11.1-py3-none-any.whl (6.5 MB)
#0 9.378 Collecting networkx (from torch==2.0.1)
#0 9.441   Using cached https://download.pytorch.org/whl/networkx-3.0-py3-none-any.whl (2.0 MB)
#0 9.884 Collecting jinja2 (from torch==2.0.1)
#0 9.902   Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
#0 10.03 Collecting triton==2.0.0 (from torch==2.0.1)
#0 10.74   Using cached https://download.pytorch.org/whl/triton-2.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (63.3 MB)
#0 11.28 Collecting cmake (from triton==2.0.0->torch==2.0.1)
#0 11.55   Using cached https://download.pytorch.org/whl/cmake-3.25.0-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.7 MB)
#0 12.03 Collecting lit (from triton==2.0.0->torch==2.0.1)
#0 12.03   Using cached lit-15.0.7-py3-none-any.whl
#0 12.46 Collecting numpy (from torchvision)
#0 12.68   Using cached https://download.pytorch.org/whl/numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
#0 13.14 Collecting requests (from torchvision)
#0 13.16   Using cached https://download.pytorch.org/whl/requests-2.28.1-py3-none-any.whl (62 kB)
#0 13.60 Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
#0 13.65   Using cached https://download.pytorch.org/whl/Pillow-9.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
#0 14.11 Collecting MarkupSafe>=2.0 (from jinja2->torch==2.0.1)
#0 14.13   Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
#0 14.59 Collecting charset-normalizer<3,>=2 (from requests->torchvision)
#0 14.61   Using cached https://download.pytorch.org/whl/charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
#0 14.73 Collecting idna<4,>=2.5 (from requests->torchvision)
#0 14.75   Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
#0 15.18 Collecting urllib3<1.27,>=1.21.1 (from requests->torchvision)
#0 15.20   Using cached https://download.pytorch.org/whl/urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
#0 15.63 Collecting certifi>=2017.4.17 (from requests->torchvision)
#0 15.65   Using cached https://download.pytorch.org/whl/certifi-2022.12.7-py3-none-any.whl (155 kB)
#0 16.09 Collecting mpmath>=0.19 (from sympy->torch==2.0.1)
#0 16.11   Using cached https://download.pytorch.org/whl/mpmath-1.2.1-py3-none-any.whl (532 kB)
#0 16.33 Installing collected packages: mpmath, lit, cmake, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, triton, torch, torchvision
#0 34.96 ERROR: Exception:
#0 34.96 Traceback (most recent call last):
#0 34.96   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
#0 34.96     status = run_func(*args)
#0 34.96   File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
#0 34.96     return func(self, options, args)
#0 34.96   File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 449, in run
#0 34.96     installed = install_given_reqs(
#0 34.96   File "/usr/local/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 72, in install_given_reqs
#0 34.96     requirement.install(
#0 34.96   File "/usr/local/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 800, in install
#0 34.96     install_wheel(
#0 34.96   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 731, in install_wheel
#0 34.96     _install_wheel(
#0 34.96   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 591, in _install_wheel
#0 34.96     file.save()
#0 34.96   File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 390, in save
#0 34.96     shutil.copyfileobj(f, dest)
#0 34.96   File "/usr/local/lib/python3.10/shutil.py", line 195, in copyfileobj
#0 34.96     buf = fsrc_read(length)
#0 34.96   File "/usr/local/lib/python3.10/zipfile.py", line 925, in read
#0 34.96     data = self._read1(n)
#0 34.96   File "/usr/local/lib/python3.10/zipfile.py", line 1015, in _read1
#0 34.96     self._update_crc(data)
#0 34.96   File "/usr/local/lib/python3.10/zipfile.py", line 943, in _update_crc
#0 34.96     raise BadZipFile("Bad CRC-32 for file %r" % self.name)
#0 34.96 zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/libtorch_cuda.so'
------
failed to solve: process "/bin/sh -c aria2c -x 5 --dir /cache --out torch-2.0.1-cp310-cp310-linux_x86_64.whl -c   https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-linux_x86_64.whl &&   pip install /cache/torch-2.0.1-cp310-cp310-linux_x86_64.whl torchvision --index-url https://download.pytorch.org/whl/cu118" did not complete successfully: exit code: 2
```
**Which UI**

auto

**Steps to Reproduce**

docker compose --profile auto up --build

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by Abdullah-AlAttar** [comment]
NVM, I interrupted the download before. and it was using the incomplete downloaded cached file.
