### ISSUE TITLE
Bug Report：Seems we need to update webui commit version

### ISSUE THREAD

**Issue by FavorMylikes** [AbdBarho/stable-diffusion-webui-docker#528]
Is there any one got this bug?

```console
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x00000243ABD4FB50>]: ValueError
Traceback (most recent call last):
  File "D:\sd original\stable-diffusion-webui\modules\extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "D:\sd original\stable-diffusion-webui\extensions-builtin\Lora\extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "D:\sd original\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 214, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "D:\sd original\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 139, in load_lora
    key_diffusers_without_lora_parts, lora_key = key_diffusers.split(".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

## Related Issue

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9478

**Comment by FavorMylikes** [comment]
Have a look for this [post ](https://www.reddit.com/r/SDtechsupport/comments/128tsh6/comment/jichqae/?utm_source=share&utm_medium=web2x&context=3)

**Comment by FavorMylikes** [comment]
## Related Commit

It looks an update about supporting Lora on sd2

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/650ddc9dd3c1d126221682be8270f7fba1b5b6ce
