### ISSUE TITLE
Python module error while using Image Lab in hlky interface : ModuleNotFoundError: No module named 'gfpgan.archs.stylegan2_cleanonnx_arch' 

### ISSUE THREAD

**Issue by greycubesgav** [AbdBarho/stable-diffusion-webui-docker#53]
**Has this issue been opened before? Check the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Main), the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=is%3Aissue) and in [the issues in the WebUI repo](https://github.com/hlky/stable-diffusion-webui)**

Nothing related found

**Describe the bug**
Python module error when trying to use  Image Lab tab under hulk interface

```
ModuleNotFoundError: No module named 'gfpgan.archs.stylegan2_cleanonnx_arch'
```

**Steps to Reproduce**
* Build and run hlky interface
```
docker compose --profile download up --build
docker compose --profile hlky up --build
```
* Browse to Image Lab tab of web interface
* Upload image to left hand "Single Image" tab
* Select "Fix Face" & "Upscale" on Processor Selection right hand. tab.
* Click "Process" button.
* Error appears in docker compose logs
```
webui-docker-hlky-1  | Traceback (most recent call last):
webui-docker-hlky-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
webui-docker-hlky-1  |     output = await app.blocks.process_api(
webui-docker-hlky-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
webui-docker-hlky-1  |     predictions, duration = await self.call_function(fn_index, processed_input)
webui-docker-hlky-1  |   File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
webui-docker-hlky-1  |     prediction = await anyio.to_thread.run_sync(
webui-docker-hlky-1  |   File "/opt/conda/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
webui-docker-hlky-1  |     return await get_asynclib().run_sync_in_worker_thread(
webui-docker-hlky-1  |   File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
webui-docker-hlky-1  |     return await future
webui-docker-hlky-1  |   File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
webui-docker-hlky-1  |     result = context.run(func, *args)
webui-docker-hlky-1  |   File "scripts/webui.py", line 1838, in imgproc
webui-docker-hlky-1  |     ModelLoader(['GFPGAN'],True,False) # Load used models
webui-docker-hlky-1  |   File "scripts/webui.py", line 1935, in ModelLoader
webui-docker-hlky-1  |     global_vars[m] = load_GFPGAN()
webui-docker-hlky-1  |   File "scripts/webui.py", line 317, in load_GFPGAN
webui-docker-hlky-1  |     from gfpgan import GFPGANer
webui-docker-hlky-1  |   File "/stable-diffusion/src/gfpgan/gfpgan/__init__.py", line 2, in <module>
webui-docker-hlky-1  |     from .archs import *
webui-docker-hlky-1  |   File "/stable-diffusion/src/gfpgan/gfpgan/archs/__init__.py", line 10, in <module>
webui-docker-hlky-1  |     _arch_modules = [importlib.import_module(f'gfpgan.archs.{file_name}') for file_name in arch_filenames]
webui-docker-hlky-1  |   File "/stable-diffusion/src/gfpgan/gfpgan/archs/__init__.py", line 10, in <listcomp>
webui-docker-hlky-1  |     _arch_modules = [importlib.import_module(f'gfpgan.archs.{file_name}') for file_name in arch_filenames]
webui-docker-hlky-1  |   File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
webui-docker-hlky-1  |     return _bootstrap._gcd_import(name[level:], package, level)
webui-docker-hlky-1  |   File "/stable-diffusion/src/gfpgan/gfpgan/archs/gfpganv1_cleanonnx_arch.py", line 8, in <module>
webui-docker-hlky-1  |     from .stylegan2_cleanonnx_arch import StyleGAN2GeneratorCleanONNX
webui-docker-hlky-1  | ModuleNotFoundError: No module named 'gfpgan.archs.stylegan2_cleanonnx_arch'
```

**Hardware / Software:**
 - OS: Ubuntu 22.04.1 LTS
 - GPU: RTX 2060
 - Version: Docker 20.10.17, latest pull of AbdBarho/stable-diffusion-webui-docker repo Mon 12th Sep '22

**Additional context**
Text-to-image prompts work fine.

**Comment by AbdBarho** [comment]
@greycubesgav the file that is missing has been deleted around 4 hours ago, or roughly one hour before you reported the issue:
https://github.com/TencentARC/GFPGAN/commit/bb2f916764923426aafdcb5aba4ad3631a52d87a

This is due to the fact that the repository is defined as pip package with no version https://github.com/sd-webui/stable-diffusion-webui/blob/7623a5734740025d79b710f3744bff9276e1467b/environment.yaml#L38

weirdly enough, I re-built the image from scratch, I could not reproduce the problem, so maybe it was fixed in later commits?

Can you retry now from scratch? i.e. `docker compose --profile hlky build --no-cache`
If it is not fixed, I would add a manual pip install command with a specific sha in the docker file
```
pip install -e git+https://github.com/TencentARC/GFPGAN@8d2447a2d918f8eba5a4a01463fd48e45126a379#egg=GFPGAN
```
