### ISSUE TITLE
TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.

### ISSUE THREAD

**Issue by knoppmyth** [AbdBarho/stable-diffusion-webui-docker#532]
**Has this issue been opened before?**

- [x ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Cannot generate image

**Which UI**

auto

**Hardware / Software**

- OS: Arch Linux
- OS version: Rolling (no LSB version)
- Docker Version: 24.0.2
- Docker compose version: 2.19.0
- Repo version: from master
- RAM: 32GB
- GPU/VRAM: RTX 2070 Super 8GB

**Steps to Reproduce**

1. docker compose --profile download up --build && docker compose --profile auto up --build
2. Navigated to localhost:7860
3. Type in "Batman and Robin" <alt><enter>
4. Noted this error in UI:`TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.
Time taken: 0.01s Torch active/reserved: 1/2 MiB, Sys VRAM: 1417/7973 MiB (17.77%) `
5. Error in terminal: ` webui-docker-auto-1  | Error completing request
webui-docker-auto-1  | Arguments: ('task(cjmwj5dp09gczer)', 'batman and robin', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, 'from modules.processing import process_images\n\np.width = 768\np.height = 768\np.batch_size = 2\np.steps = 10\n\nreturn process_images(p)', 2, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/call_queue.py", line 57, in f
webui-docker-auto-1  |     res = list(func(*args, **kwargs))
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/call_queue.py", line 37, in f
webui-docker-auto-1  |     res = func(*args, **kwargs)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/txt2img.py", line 57, in txt2img
webui-docker-auto-1  |     processed = processing.process_images(p)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/processing.py", line 611, in process_images
webui-docker-auto-1  |     res = process_images_inner(p)
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/processing.py", line 675, in process_images_inner
webui-docker-auto-1  |     sd_vae_approx.model()
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/sd_vae_approx.py", line 42, in model
webui-docker-auto-1  |     sd_vae_approx_model.load_state_dict(torch.load(model_path, map_location='cpu' if devices.device.type != 'cuda' else None))
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1994, in load_state_dict
webui-docker-auto-1  |     raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
webui-docker-auto-1  | TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.
webui-docker-auto-1  | 
`

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by knoppmyth** [comment]
I need to drop model.pt in the VAE-approx folder.
