### ISSUE TITLE
I updated to the latest version, but the same error still occurs."

### ISSUE THREAD

**Issue by horoabb** [AbdBarho/stable-diffusion-webui-docker#613]
I updated to the latest version, but the same error still occurs."

#TypeError：AsyncConnectionPool。init () 收到意外的關鍵字參數 'socket_options

**Comment by zmlgit** [comment]
same here!


webui-docker-auto-1  | Installing extension dependencies (if any)
webui-docker-auto-1  | Traceback (most recent call last):
webui-docker-auto-1  |   File "/stable-diffusion-webui/webui.py", line 44, in <module>
webui-docker-auto-1  |     import gradio  # noqa: F401
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
webui-docker-auto-1  |     import gradio.components as components
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/components.py", line 55, in <module>
webui-docker-auto-1  |     from gradio import processing_utils, utils
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 339, in <module>
webui-docker-auto-1  |     class AsyncRequest:
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 358, in AsyncRequest
webui-docker-auto-1  |     client = httpx.AsyncClient()
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1397, in __init__
webui-docker-auto-1  |     self._transport = self._init_transport(
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1445, in _init_transport
webui-docker-auto-1  |     return AsyncHTTPTransport(
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 275, in __init__
webui-docker-auto-1  |     self._pool = httpcore.AsyncConnectionPool(
webui-docker-auto-1  | TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
webui-docker-auto-1 exited with code 1
`
`
