### ISSUE TITLE
Attempt to run today with failure 

### ISSUE THREAD

**Issue by kraoc** [AbdBarho/stable-diffusion-webui-docker#626]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Try to build & run from scratch after git clone.

**Which UI**

auto

**Hardware / Software**

- OS: Archlinux
- OS version: rolling release
- WSL version (if applicable): 
- Docker Version: 24.0.7
- Docker compose version: 2.23.3
- Repo version: "from master" 
- RAM: 32G
- GPU/VRAM: 12G

**Steps to Reproduce**

docker compose --profile auto up --build -d

**Additional context**

```ounted embeddings
Mounted .cache
Mounted styles.csv
Mounted ui-config.json
Mounted models
Mounted .cache
Mounted config_states
Mounted config.json
Mounted extensions
Installing extension dependencies (if any)
Traceback (most recent call last):
  File "/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/stable-diffusion-webui/modules/initialize.py", line 37, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/stable-diffusion-webui/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet
  File "/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 3, in <module>
    import psutil
  File "/opt/conda/lib/python3.10/site-packages/psutil/__init__.py", line 241, in <module>
    raise ImportError(msg)
ImportError: version conflict: '/opt/conda/lib/python3.10/site-packages/psutil/_psutil_linux.cpython-310-x86_64-linux-gnu.so' C extension module was built for another version of psutil (5.9.0 instead of 5.9.5); you may try to 'pip uninstall psutil', manually remove /opt/conda/lib/python3.10/site-packages/psutil/_psutil_linux.cpython-310-x86_64-linux-gnu.so or clean the virtual env somehow, then reinstall
```

**Solution founded**

Edit **services/AUTOMATIC1111/Dockerfile** line 45 to add

```
RUN  --mount=type=cache,target=/root/.cache/pip pip install psutil==5.9.0
```

With this added, got

```
Startup time: 5.1s (import torch: 1.8s, import gradio: 0.7s, setup paths: 0.8s, initialize shared: 0.1s, other imports: 0.5s, load scripts: 0.3s, create ui: 0.3s, gradio launch: 0.2s).
```

So it works now.

**Comment by AbdBarho** [comment]
I updated the base container image today, and cannot reproduce the problem.

Could you please try again? thank you.
