### ISSUE TITLE
I update 1.6 to 1.7 

### ISSUE THREAD

**Issue by horoabb** [AbdBarho/stable-diffusion-webui-docker#667]
The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.: str
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/errors.py", line 98, in run
    code()
  File "/stable-diffusion-webui/modules/devices.py", line 76, in enable_tf32
    device_id = (int(shared.cmd_opts.device_id) if shared.cmd_opts.device_id is not None and shared.cmd_opts.device_id.isdigit() else 0) or torch.cuda.current_device()
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 769, in current_device
    _lazy_init()
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/stable-diffusion-webui/modules/initialize.py", line 34, in imports
    shared_init.initialize()
  File "/stable-diffusion-webui/modules/shared_init.py", line 17, in initialize
    from modules import options, shared_options
  File "/stable-diffusion-webui/modules/shared_options.py", line 3, in <module>
    from modules import localization, ui_components, shared_items, shared, interrogate, shared_gradio_themes
  File "/stable-diffusion-webui/modules/interrogate.py", line 13, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "/stable-diffusion-webui/modules/devices.py", line 84, in <module>
    errors.run(enable_tf32, "Enabling TF32")
  File "/stable-diffusion-webui/modules/errors.py", line 100, in run
    display(task, e)
  File "/stable-diffusion-webui/modules/errors.py", line 68, in display
    te = traceback.TracebackException.from_exception(e)
  File "/opt/conda/lib/python3.10/traceback.py", line 572, in from_exception
    return cls(type(exc), exc, exc.__traceback__, *args, **kwargs)
AttributeError: 'str' object has no attribute '__traceback__'

**Comment by jsjolund** [comment]
1. What version of the Nvidia driver do you have?

2. Why did you not follow the bug report template?



**Has this issue been opened before?**

- [ ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**



**Which UI**

auto or auto-cpu or invoke or comfy?

**Hardware / Software**

- OS: [e.g. Windows 10 / Ubuntu 22.04]
- OS version: 
- WSL version (if applicable): 
- Docker Version: 
- Docker compose version: 
- Repo version: 
- RAM:
- GPU/VRAM:

**Steps to Reproduce**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.
