### ISSUE TITLE
Model Checkpoint Not Found: Unable to Load Stable Diffusion Model

### ISSUE THREAD

**Issue by bachng0111** [AbdBarho/stable-diffusion-webui-docker#721]
Hi,

I have error when running "docker compose --profile auto-cpu up --build"
FileNotFoundError: No checkpoints found. When searching for checkpoints, looked at:
auto-cpu-1  |  - file /stable-diffusion-webui/model.ckpt
auto-cpu-1  |  - directory /stable-diffusion-webui/models/Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.

**Hardware / Software**

- OS:  Windows 10 
- OS version: 22H2
- Docker Version: Rancher Desktop 1.13.1, Client 25.0.4-rd, Engine 25.0.3
- Docker compose version: v2.24.7
- Repo version:  from master

```
auto-cpu-1  | loading stable diffusion model: FileNotFoundError
auto-cpu-1  | Traceback (most recent call last):
auto-cpu-1  |   File "/opt/conda/lib/python3.10/threading.py", line 973, in _bootstrap
auto-cpu-1  |     self._bootstrap_inner()
auto-cpu-1  |   File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
auto-cpu-1  |     self.run()
auto-cpu-1  |   File "/opt/conda/lib/python3.10/threading.py", line 953, in run
auto-cpu-1  |     self._target(*self._args, **self._kwargs)
auto-cpu-1  |   File "/stable-diffusion-webui/modules/initialize.py", line 149, in load_model
auto-cpu-1  |     shared.sd_model  # noqa: B018
auto-cpu-1  |   File "/stable-diffusion-webui/modules/shared_items.py", line 175, in sd_model
auto-cpu-1  |     return modules.sd_models.model_data.get_sd_model()
auto-cpu-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 620, in get_sd_model
auto-cpu-1  |     load_model()
auto-cpu-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 691, in load_model
auto-cpu-1  |     checkpoint_info = checkpoint_info or select_checkpoint()
auto-cpu-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 224, in select_checkpoint
auto-cpu-1  |     raise FileNotFoundError(error_message)
auto-cpu-1  | FileNotFoundError: No checkpoints found. When searching for checkpoints, looked at:
auto-cpu-1  |  - file /stable-diffusion-webui/model.ckpt
auto-cpu-1  |  - directory /stable-diffusion-webui/models/Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.
```

**Comment by fcurti-ar** [comment]
Same issue here
