### ISSUE TITLE
ImportError: cannot import name 'TypeIs' from 'typing_extensions'

### ISSUE THREAD

**Issue by makkarss929** [AbdBarho/stable-diffusion-webui-docker#722]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Attaching to auto-cpu-1
auto-cpu-1  | /stable-diffusion-webui
auto-cpu-1  | total 772K
auto-cpu-1  | drwxr-xr-x  1 root root 4.0K Aug 12 16:43 .
auto-cpu-1  | drwxr-xr-x  1 root root 4.0K Aug 16 09:04 ..
auto-cpu-1  | -rw-r--r--  1 root root   48 Aug 12 16:42 .eslintignore
auto-cpu-1  | -rw-r--r--  1 root root 3.4K Aug 12 16:42 .eslintrc.js
auto-cpu-1  | drwxr-xr-x  8 root root 4.0K Aug 12 16:42 .git
auto-cpu-1  | -rw-r--r--  1 root root   55 Aug 12 16:42 .git-blame-ignore-revs
auto-cpu-1  | drwxr-xr-x  4 root root 4.0K Aug 12 16:42 .github
auto-cpu-1  | -rw-r--r--  1 root root  521 Aug 12 16:42 .gitignore
auto-cpu-1  | -rw-r--r--  1 root root  119 Aug 12 16:42 .pylintrc
auto-cpu-1  | -rw-r--r--  1 root root  84K Aug 12 16:42 CHANGELOG.md
auto-cpu-1  | -rw-r--r--  1 root root  243 Aug 12 16:42 CITATION.cff
auto-cpu-1  | -rw-r--r--  1 root root  657 Aug 12 16:42 CODEOWNERS
auto-cpu-1  | -rw-r--r--  1 root root  35K Aug 12 16:42 LICENSE.txt
auto-cpu-1  | -rw-r--r--  1 root root  13K Aug 12 16:42 README.md
auto-cpu-1  | -rw-r--r--  1 root root  146 Aug 12 16:42 _typos.toml
auto-cpu-1  | drwxr-xr-x  2 root root 4.0K Aug 12 16:42 configs
auto-cpu-1  | drwxr-xr-x  2 root root 4.0K Aug 12 16:42 embeddings
auto-cpu-1  | -rw-r--r--  1 root root  167 Aug 12 16:42 environment-wsl2.yaml
auto-cpu-1  | drwxr-xr-x  2 root root 4.0K Aug 12 16:42 extensions
auto-cpu-1  | drwxr-xr-x 13 root root 4.0K Aug 12 16:42 extensions-builtin
auto-cpu-1  | drwxr-xr-x  2 root root 4.0K Aug 12 16:42 html
auto-cpu-1  | drwxr-xr-x  2 root root 4.0K Aug 12 16:43 interrogate
auto-cpu-1  | drwxr-xr-x  2 root root 4.0K Aug 12 16:42 javascript
auto-cpu-1  | -rw-r--r--  1 root root 1.3K Aug 12 16:42 launch.py
auto-cpu-1  | drwxr-xr-x  2 root root 4.0K Aug 12 16:42 localizations
auto-cpu-1  | drwxr-xr-x  7 root root 4.0K Aug 12 16:42 models
auto-cpu-1  | drwxr-xr-x  7 root root 4.0K Aug 12 16:42 modules
auto-cpu-1  | -rw-r--r--  1 root root  185 Aug 12 16:42 package.json
auto-cpu-1  | -rw-r--r--  1 root root  841 Aug 12 16:42 pyproject.toml
auto-cpu-1  | drwxr-xr-x  8 root root 4.0K Aug 12 16:39 repositories
auto-cpu-1  | -rw-r--r--  1 root root   49 Aug 12 16:42 requirements-test.txt
auto-cpu-1  | -rw-r--r--  1 root root  371 Aug 12 16:42 requirements.txt
auto-cpu-1  | -rw-r--r--  1 root root   42 Aug 12 16:42 requirements_npu.txt
auto-cpu-1  | -rw-r--r--  1 root root  645 Aug 12 16:42 requirements_versions.txt
auto-cpu-1  | -rw-r--r--  1 root root 411K Aug 12 16:42 screenshot.png
auto-cpu-1  | -rw-r--r--  1 root root 6.1K Aug 12 16:42 script.js
auto-cpu-1  | drwxr-xr-x  2 root root 4.0K Aug 12 16:42 scripts
auto-cpu-1  | -rw-r--r--  1 root root  43K Aug 12 16:42 style.css
auto-cpu-1  | drwxr-xr-x  4 root root 4.0K Aug 12 16:42 test
auto-cpu-1  | drwxr-xr-x  2 root root 4.0K Aug 12 16:42 textual_inversion_templates
auto-cpu-1  | -rw-r--r--  1 root root  670 Aug 12 16:42 webui-macos-env.sh
auto-cpu-1  | -rw-r--r--  1 root root   84 Aug 12 16:42 webui-user.bat
auto-cpu-1  | -rw-r--r--  1 root root 1.4K Aug 12 16:42 webui-user.sh
auto-cpu-1  | -rw-r--r--  1 root root 2.3K Aug 12 16:42 webui.bat
auto-cpu-1  | -rw-r--r--  1 root root 5.3K Aug 12 16:42 webui.py
auto-cpu-1  | -rwxr-xr-x  1 root root  11K Aug 12 16:42 webui.sh
auto-cpu-1  | ./
auto-cpu-1  | model.pt
auto-cpu-1  | ./
auto-cpu-1  | ViT-L-14_stats.th
auto-cpu-1  | Mounted .cache
auto-cpu-1  | mkdir: created directory '/data/config/auto/config_states'
auto-cpu-1  | Mounted config_states
auto-cpu-1  | mkdir: created directory '/stable-diffusion-webui/repositories/CodeFormer'
auto-cpu-1  | mkdir: created directory '/stable-diffusion-webui/repositories/CodeFormer/weights'
auto-cpu-1  | Mounted .cache
auto-cpu-1  | Mounted embeddings
auto-cpu-1  | Mounted config.json
auto-cpu-1  | Mounted models
auto-cpu-1  | Mounted styles.csv
auto-cpu-1  | Mounted ui-config.json
auto-cpu-1  | mkdir: created directory '/data/config/auto/extensions'
auto-cpu-1  | Mounted extensions
auto-cpu-1  | Installing extension dependencies (if any)
auto-cpu-1  | Traceback (most recent call last):
auto-cpu-1  |   File "/stable-diffusion-webui/webui.py", line 13, in <module>
auto-cpu-1  |     initialize.imports()
auto-cpu-1  |   File "/stable-diffusion-webui/modules/initialize.py", line 23, in imports
auto-cpu-1  |     import gradio  # noqa: F401
auto-cpu-1  |   File "/opt/conda/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
auto-cpu-1  |     import gradio.components as components
auto-cpu-1  |   File "/opt/conda/lib/python3.10/site-packages/gradio/components/__init__.py", line 3, in <module>
auto-cpu-1  |     from gradio.components.bar_plot import BarPlot
auto-cpu-1  |   File "/opt/conda/lib/python3.10/site-packages/gradio/components/bar_plot.py", line 7, in <module>
auto-cpu-1  |     import altair as alt
auto-cpu-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/__init__.py", line 650, in <module>
auto-cpu-1  |     from altair.vegalite import *
auto-cpu-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/vegalite/__init__.py", line 2, in <module>
auto-cpu-1  |     from .v5 import *
auto-cpu-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/vegalite/v5/__init__.py", line 2, in <module>
auto-cpu-1  |     from altair.expr.core import datum
auto-cpu-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/expr/__init__.py", line 7, in <module>
auto-cpu-1  |     from altair.expr.core import ConstExpression, FunctionExpression
auto-cpu-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/expr/core.py", line 6, in <module>
auto-cpu-1  |     from altair.utils import SchemaBase
auto-cpu-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/utils/__init__.py", line 15, in <module>
auto-cpu-1  |     from .plugin_registry import PluginRegistry
auto-cpu-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/utils/plugin_registry.py", line 6, in <module>
auto-cpu-1  |     from typing_extensions import TypeAliasType, TypeIs, TypeVar
auto-cpu-1  | ImportError: cannot import name 'TypeIs' from 'typing_extensions' (/opt/conda/lib/python3.10/site-packages/typing_extensions.py)
auto-cpu-1 exited with code 1

**Which UI**

auto-cpu?

**Hardware / Software**

- OS: ubuntu
- OS version: 
- Docker Version: 
- Docker compose version: 
- Repo version: 
- RAM:
- GPU/VRAM:

**Steps to Reproduce**

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by DynoW** [comment]
Try the solution of **yasu-nxt** in #719

**Comment by T0T4R4** [comment]
Identical tickets : #719 , #729 , #742
