### ISSUE TITLE
After building to run, get 12 file errors and ImportError

### ISSUE THREAD

**Issue by F1zzyD** [AbdBarho/stable-diffusion-webui-docker#729]
**Has this issue been opened before?**

- [ x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Followed the directions to install using docker. Step two of building and running fails with the following output during a clean install:
auto-1  | Traceback (most recent call last):
auto-1  |   File "/stable-diffusion-webui/webui.py", line 13, in <module>
auto-1  |     initialize.imports()
auto-1  |   File "/stable-diffusion-webui/modules/initialize.py", line 23, in imports
auto-1  |     import gradio  # noqa: F401
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
auto-1  |     import gradio.components as components
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/gradio/components/__init__.py", line 3, in <module>
auto-1  |     from gradio.components.bar_plot import BarPlot
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/gradio/components/bar_plot.py", line 7, in <module>
auto-1  |     import altair as alt
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/__init__.py", line 650, in <module>
auto-1  |     from altair.vegalite import *
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/vegalite/__init__.py", line 2, in <module>
auto-1  |     from .v5 import *
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/vegalite/v5/__init__.py", line 2, in <module>
auto-1  |     from altair.expr.core import datum
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/expr/__init__.py", line 7, in <module>
auto-1  |     from altair.expr.core import ConstExpression, FunctionExpression
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/expr/core.py", line 6, in <module>
auto-1  |     from altair.utils import SchemaBase
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/utils/__init__.py", line 14, in <module>
auto-1  |     from .plugin_registry import PluginRegistry
auto-1  |   File "/opt/conda/lib/python3.10/site-packages/altair/utils/plugin_registry.py", line 6, in <module>
auto-1  |     from typing_extensions import TypeAliasType, TypeIs, TypeVar
auto-1  | ImportError: cannot import name 'TypeIs' from 'typing_extensions' (/opt/conda/lib/python3.10/site-packages/typing_extensions.py)

**Which UI**

Auto

**Hardware / Software**

- OS: [e.g. Windows 10 / **Ubuntu 22.04]**
- OS version: Ubuntu 22.04
- Docker Version: 27.2.0
- Docker compose version: 2.29.2
- Repo version: from master
- RAM: 32
- GPU/VRAM: Not applicable

**Steps to Reproduce**

1. Go to the install guide
2. Click on follow step 1 with no error. 
3. Follow step two to receive error.

**Additional context**
Just really frustrating to see that all guides on how to install Stable Diffusion WebUI are either outdated or broken for Linux. Can't seem to find anything that works.

**Comment by Jonpro03** [comment]
This might actually be a AUTOMATIC1111 problem, but I worked around it by adding `pip install --upgrade typing-extensions` to `services/AUTOMATIC1111/Dockerfile` right after the existing requirements file install.

```Dockerfile
WORKDIR /
RUN --mount=type=cache,target=/root/.cache/pip \
  git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git && \
  cd stable-diffusion-webui && \
  git reset --hard v1.9.4 && \
  pip install -r requirements_versions.txt && \
  pip install --upgrade typing-extensions
```

again, not a fix but will unblock anyone else dealing with this

**Comment by epsilonion-liam** [comment]
go to the services/AUTOMATIC1111 directory in the cloned repo and add

the walk around to that Dockerfile

got a little confused there  lol ty for the walkaround.. :P does not take a lot to confuse me these days (old git here).

**Comment by T0T4R4** [comment]
Identical tickets : #719  , #722 , #742

**Comment by pterodactyl-soup** [comment]
same issue still its dec 13 2024, and had to not only do this but also disable my firewall on windows 11 during download, and add in code in another place for issue #657, hopefully someone sees that they need to do all 3 things for it to work. yes i see automatic1111 is partly responsible for this breaking thank you to those sharing this info.

So confused what people are using, youtubing and redditing recent top things and this comes up but no one non technical would be able to get past these steps
