### ISSUE TITLE
Compose build crashes

### ISSUE THREAD

**Issue by King0Kr** [AbdBarho/stable-diffusion-webui-docker#97]
I hope you guys can help me
I have been through the FAQ and the Issues list but don't see my problem listed.

I have applied all fixes from the FAQ and saw that there is a problem with 16GB RAM so I have set it to use 12.

System specs:
Processor	AMD Ryzen 7 5800X 8-Core Processor                3.80 GHz
GPU Nvidia RTX 2070
GPU Driver version 516.94 Game Ready
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor

Windows specs:
Edition	Windows 11 Pro
Version	21H2
OS build	22000.978
Experience	Windows Feature Experience Pack 1000.22000.978.0

I see the docker container spike to 8GB RAM usage then crashes.

I get the following error running (docker compose --profile auto up --build):

PS C:\stablediffusion\stable-diffusion-webui-docker-1.1.1\stable-diffusion-webui-docker-1.1.1> docker compose --profile auto up --build
[+] Building 4.4s (27/27) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                         2.3s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ce  0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => [internal] load build definition from Dockerfile                                                               0.0s
 => [internal] load metadata for docker.io/continuumio/miniconda3:4.12.0                                           1.5s
 => [internal] load metadata for docker.io/alpine/git:2.36.2                                                       1.8s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 118B                                                                                  0.0s
 => [download 1/5] FROM docker.io/alpine/git:2.36.2@sha256:3ad0f6025feea6c01f552e467989a79a057176c06a9f266de440be  0.0s
 => [stage-1  1/12] FROM docker.io/continuumio/miniconda3:4.12.0@sha256:977263e8d1e476972fddab1c75fe050dd3cd17626  0.0s
 => CACHED [stage-1  2/12] RUN conda install python=3.8.5 && conda clean -a -y                                     0.0s
 => CACHED [stage-1  3/12] RUN conda install pytorch==1.11.0 torchvision==0.12.0 cudatoolkit=11.3 -c pytorch && c  0.0s
 => CACHED [stage-1  4/12] RUN apt-get update && apt install fonts-dejavu-core rsync -y && apt-get clean           0.0s
 => CACHED [stage-1  5/12] RUN <<EOF (git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git...)    0.0s
 => CACHED [download 2/5] RUN git clone --depth 1 https://github.com/CompVis/stable-diffusion.git repositories/st  0.0s
 => CACHED [download 3/5] RUN git clone --depth 1 https://github.com/sczhou/CodeFormer.git repositories/CodeForme  0.0s
 => CACHED [download 4/5] RUN git clone --depth 1 https://github.com/salesforce/BLIP.git repositories/BLIP         0.0s
 => CACHED [download 5/5] RUN <<EOF (# because taming-transformers is huge...)                                     0.0s
 => CACHED [stage-1  6/12] COPY --from=download /git/ /stable-diffusion-webui                                      0.0s
 => CACHED [stage-1  7/12] RUN pip install --prefer-binary --no-cache-dir -r /stable-diffusion-webui/repositories  0.0s
 => CACHED [stage-1  8/12] RUN <<EOF (cd stable-diffusion-webui...)                                                0.0s
 => CACHED [stage-1  9/12] RUN pip install --prefer-binary -U --no-cache-dir opencv-python-headless                0.0s
 => CACHED [stage-1 10/12] COPY . /docker                                                                          0.0s
 => CACHED [stage-1 11/12] RUN chmod +x /docker/mount.sh && python3 /docker/info.py /stable-diffusion-webui/modul  0.0s
 => CACHED [stage-1 12/12] WORKDIR /stable-diffusion-webui/repositories/stable-diffusion                           0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:ce23da7fbfab4c895f7512e4acb93a1d8fae6574279521864dc31169c8549bbe                       0.0s
 => => naming to docker.io/library/webui-docker-automatic1111                                                      0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 1/0
 - Container webui-docker-automatic1111-1  Created                                                                 0.0s
Attaching to webui-docker-automatic1111-1
webui-docker-automatic1111-1  | + /docker/mount.sh
webui-docker-automatic1111-1  | Mounted model.ckpt
webui-docker-automatic1111-1  | Mounted GFPGANv1.3.pth
webui-docker-automatic1111-1  | + python3 -u ../../webui.py --listen --port 7860 --hide-ui-dir-config --ckpt-dir /cache/custom-models --ckpt /cache/models/model.ckpt --medvram
webui-docker-automatic1111-1  | LatentDiffusion: Running in eps-prediction mode
webui-docker-automatic1111-1  | DiffusionWrapper has 859.52 M params.
webui-docker-automatic1111-1  | making attention of type 'vanilla' with 512 in_channels
webui-docker-automatic1111-1  | Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
webui-docker-automatic1111-1  | making attention of type 'vanilla' with 512 in_channels
webui-docker-automatic1111-1  | Traceback (most recent call last):
webui-docker-automatic1111-1  |   File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 371, in load_state_dict
webui-docker-automatic1111-1  |     return torch.load(checkpoint_file, map_location="cpu")
webui-docker-automatic1111-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 705, in load
webui-docker-automatic1111-1  |     with _open_zipfile_reader(opened_file) as opened_zipfile:
webui-docker-automatic1111-1  |   File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 243, in __init__
webui-docker-automatic1111-1  |     super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
webui-docker-automatic1111-1  | RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
webui-docker-automatic1111-1  |
webui-docker-automatic1111-1  | During handling of the above exception, another exception occurred:
webui-docker-automatic1111-1  |
webui-docker-automatic1111-1  | Traceback (most recent call last):
webui-docker-automatic1111-1  |   File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 375, in load_state_dict
webui-docker-automatic1111-1  |     if f.read().startswith("version"):
webui-docker-automatic1111-1  |   File "/opt/conda/lib/python3.8/codecs.py", line 322, in decode
webui-docker-automatic1111-1  |     (result, consumed) = self._buffer_decode(data, self.errors, final)
webui-docker-automatic1111-1  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
webui-docker-automatic1111-1  |
webui-docker-automatic1111-1  | During handling of the above exception, another exception occurred:
webui-docker-automatic1111-1  |
webui-docker-automatic1111-1  | Traceback (most recent call last):
webui-docker-automatic1111-1  |   File "../../webui.py", line 67, in <module>
webui-docker-automatic1111-1  |     shared.sd_model = modules.sd_models.load_model()
webui-docker-automatic1111-1  |   File "/stable-diffusion-webui/modules/sd_models.py", line 117, in load_model
webui-docker-automatic1111-1  |     sd_model = instantiate_from_config(sd_config.model)
webui-docker-automatic1111-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
webui-docker-automatic1111-1  |     return get_obj_from_str(config["target"])(**config.get("params", dict()))
webui-docker-automatic1111-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 461, in __init__
webui-docker-automatic1111-1  |     self.instantiate_cond_stage(cond_stage_config)
webui-docker-automatic1111-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 519, in instantiate_cond_stage
webui-docker-automatic1111-1  |     model = instantiate_from_config(config)
webui-docker-automatic1111-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/util.py", line 85, in instantiate_from_config
webui-docker-automatic1111-1  |     return get_obj_from_str(config["target"])(**config.get("params", dict()))
webui-docker-automatic1111-1  |   File "/stable-diffusion-webui/repositories/stable-diffusion/ldm/modules/encoders/modules.py", line 142, in __init__
webui-docker-automatic1111-1  |     self.transformer = CLIPTextModel.from_pretrained(version)
webui-docker-automatic1111-1  |   File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2110, in from_pretrained
webui-docker-automatic1111-1  |     state_dict = load_state_dict(resolved_archive_file)
webui-docker-automatic1111-1  |   File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 387, in load_state_dict
webui-docker-automatic1111-1  |     raise OSError(
webui-docker-automatic1111-1  | OSError: Unable to load weights from pytorch checkpoint file for '/cache/transformers/models--openai--clip-vit-large-patch14/snapshots/e45c02554b24d4c70b955be461d78a18e91d579c/pytorch_model.bin' at '/cache/transformers/models--openai--clip-vit-large-patch14/snapshots/e45c02554b24d4c70b955be461d78a18e91d579c/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by AbdBarho** [comment]
This problem means the download was interrupted and the file is incomplete, the only solution I know is to delete the corrupted file in cache/transformers/models--openai--clip-vit-large-patch14/ and restart the container. It will retry the download again, if you have a bad connection (like I do) it might take a couple of tries.
